### ISSUE TITLE
Use internal redirects for linking to outside sites

### ISSUE THREAD

**Issue by Jonathan-Fort** [Jonathan-Fort/IGAIR-Web#12]
When linking to a Discord or RSI link in IGAIR-Web, perform a routing call to a on-site link before directing users off. **The site routing infrastructure should handle sending the individual off of the website, as it allows code to be executed before the individual leaves.** This reduces the chances of an XSS or man-in-the-middle attack from being successful against users VIA link scraping, and allows us to use analytics and clean up data before they close their connection to the site.

**Comment by Jonathan-Fort** [comment]
IE.
https://robertsspaceindustries.com/orgs/IGAIR -> /ext/org
https://discord.gg/zRyvbAy -> /ext/discord
https://robertsspaceindustries.com/spectrum/community/IGAIR -> /ext/spectrum

with a router configured to handle routings out to those links.

**Comment by Unikore** [comment]
The downside with the `/ext/XYZ` style is the user does not see a preview of the URL.

But out of curiosity: Those are simple links to other sites. I have not heard of these being a problem before? You mention "link scraping", but I don't see how collecting URLs from websites is related to XSS or MITM. I tried to find out via a Google search, but I failed to find anything relevant.
